services:
  app:
    build:
      context: .
      dockerfile: .docker/prod/Dockerfile
    image: strange-air:0.1
    environment:
      APP_ENV: "production"
      APP_ENV_FILE: "false"
      APP_SERVER_PORT: "8000"
    ports:
      - "8001:8000"
    networks:
      - strange-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  strange-net:
    name: strange-net
    driver: bridge