services:
  app:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    environment:
      APP_ENV: "production"
      SERVER_PORT: "8000"
    ports:
      - "8000:8000"
    networks:
      - strange-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  strange-net:
    name: strange-net
    driver: bridge